import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  row: {
    alignItems: "center",
    flexDirection: "row",
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    marginBottom: 10,
  },
  image: {
    marginTop: 60,
    marginBottom: 10,
    marginLeft: 25,
    borderRadius: 40,
    borderColor: "#E3AD6A",
    borderWidth: 1,
    width: 170,
    height: 170,
  },
  textContainer: {
    flexDirection: "column",
    alignItems: "flex-end",
  },
  yourName2: {
    marginLeft: 20,
    textAlign: "right",
    marginTop: 30,
    fontSize: 20,
  },
  work: {
    textAlign: "right",
  },
  place: {
    flexDirection: "row",
  },
  icon: {
    marginTop: 20,
  },
  icon1: {
    marginTop: 5,
    fontSize: 20,
  },
  city: {
    marginTop: 20,
    marginLeft: 10,
    textAlign: "right",
    fontSize: 20,
  },
  country: {},
  yourEmail: {
    color: "#121212",
    textDecorationLine: "underline",
    fontSize: 20,
  },

  button: {
    width: 54,
    height: 52,
  },
  iconStack: {
    top: 707,
    left: 25,
    width: 54,
    height: 52,
    position: "absolute",
  },
  icon2: {
    top: 1,
    left: 0,
    position: "absolute",
    color: "rgba(85,103,248,1)",
    fontSize: 40,
  },
  button2: {
    top: 0,
    left: 0,
    width: 40,
    height: 46,
    position: "absolute",
  },
  icon2Stack: {
    top: 712,
    left: 168,
    width: 40,
    height: 46,
    position: "absolute",
  },
  rect: {},
  icon3: {
    top: 0,
    left: 0,
    position: "absolute",
    color: "rgba(85,103,248,1)",
    fontSize: 40,
  },
  button3: {
    top: 0,
    left: 0,
    width: 40,
    height: 41,
    position: "absolute",
  },
  icon3Stack: {
    top: 715,
    left: 289,
    width: 40,
    height: 41,
    position: "absolute",
  },
  yourPassword: {
    left: 48,
    position: "absolute",
    color: "#121212",
    textDecorationLine: "underline",
    fontSize: 20,
  },

  button4: {
    width: 160,
    height: 125,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    margin: 15,
    marginTop: 30,
  },
  book: {
    marginTop: 10,
    marginLeft: 10,
    color: "rgba(255,169,9,1)",
    fontSize: 30,
  },
  lessonIcon: {
    marginTop: 10,
    marginLeft: 10,
    color: "rgba(85,103,248,1)",
    fontSize: 30,
  },
  shedduleIcon: {
    marginTop: 10,
    marginLeft: 10,
    color: "rgba(94,255,6,1)",
    fontSize: 30,
  },
  resultsIcon: {
    marginTop: 10,
    marginLeft: 10,
    color: "rgba(128,4,255,1)",
    fontSize: 30,
  },
  newsIcon: {
    marginTop: 10,
    marginLeft: 10,
    color: "rgba(255,0,0,1)",
    fontSize: 30,
  },
  profileIcon: {
    marginTop: 10,
    marginLeft: 10,
    color: "rgba(3,250,212,1)",
    fontSize: 30,
  },
  contactIcon: {
    marginTop: 10,
    marginLeft: 10,
    color: "rgba(248,247,1,1)",
    fontSize: 30,
  },
  LogOutIcon: {
    marginTop: 10,
    marginLeft: 10,
    color: "rgba(189,16,224,1)",
    fontSize: 30,
  },
  buttonText: {
    marginTop: 20,
    marginLeft: 10,
    color: "#000000",
    fontSize: 20,
  },
});
